name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
      env:
        REACT_APP_API_KEY: ${{secrets.API_KEY}}
    - run : git config user.name github-actions
    - run : git config user.email github-actions@github.com
    - run : git --work-tree build add --all
    - run : git commit -m "Automatic Deploy action run by github-actions"
    - run : git push origin HEAD:gh-pages --force
      
        
